import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@/styles/globals.css";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { theme } from "@/styles/theme";

const montserrat = Montserrat({
	variable: "--font-base",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Party Planning App",
	description: "Generated by mehdi rezaei",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${montserrat.variable}`}>
			<head>
				<ColorSchemeScript defaultColorScheme="dark" />
				<link rel="shortcut icon" href="/favicon.ico" />
				<meta
					name="viewport"
					content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
				/>
			</head>
			<body className={montserrat.className}>
				<MantineProvider defaultColorScheme="dark" theme={theme}>
					<main className="min-h-screen p-4">{children}</main>
				</MantineProvider>
			</body>
		</html>
	);
}
