import "@mantine/core/styles.css";
import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { theme } from "@/config/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Party Planning App",
	description: "Generated by mehdi rezaei",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
				<link rel="shortcut icon" href="/next.svg" />
				<meta
					name="viewport"
					content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
				/>
			</head>
			<body className={inter.className}>
				<MantineProvider theme={theme}>{children}</MantineProvider>
			</body>
		</html>
	);
}
